[env:esp32s3]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  adafruit/Adafruit MPU6050
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit NeoPixel
  pololu/VL53L0X

lib_extra_dirs = lib

upload_speed = 460800